server:
  port: 8088


medilabo:
  security:
    internal-header: "X-Internal-Secret"
    internal-secret: "MonSecretSecurise123!"

spring:
  security:
    user:
      name: "authorized-client"
      password: "SuperSecretPassword2025!"
  application:
    name: ms-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: patient-service-route
          uri: lb://MS-PATIENT
          predicates:
            - Path=/api/patient/**
          filters:
            # On rÃ©Ã©crit le chemin
            - RewritePath=/api/(?<segment>.*), /${segment}
            # ğŸ›¡ï¸ SÃ©curitÃ© : on nettoie ce qui vient de l'extÃ©rieur
            - RemoveRequestHeader=${medilabo.security.internal-header}
            # ğŸ”‘ On ajoute notre secret (en utilisant la variable du haut)
            - AddRequestHeader=${medilabo.security.internal-header}, ${medilabo.security.internal-secret}

        - id: auth-route
          uri: lb://MS-PATIENT
          predicates:
            - Path=/api/auth/**
          filters:
            # âœ… Correction de l'anti-slash ici
            - RewritePath=/api/(?<segment>.*), /${segment}
        - id: notes-service-route
          uri: lb://MS-NOTES
          predicates:
            - Path=/api/notes/**
          filters:
            - RewritePath=/api/(?<segment>.*), /${segment}
            # ğŸ›¡ï¸ SÃ©curitÃ© : on nettoie ce qui vient de l'extÃ©rieur
            - RemoveRequestHeader=${medilabo.security.internal-header}
            # ğŸ”‘ On ajoute notre secret (en utilisant la variable du haut)
            - AddRequestHeader=${medilabo.security.internal-header}, ${medilabo.security.internal-secret}