server:
  port: 8088 # Le bon port d'Ã©coute du Gateway

spring:
  application:
    name: ms-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # TrÃ¨s important pour le LB
      routes:
        - id: patient-service-route
          uri: lb://MS-PATIENT
          predicates:
            - Path=/api/patient/**
          filters:
            # ðŸ›‘ LE FILTRE CORRIGÃ‰ : Retire uniquement /api/, garde /patient/list
            - RewritePath=/api/(?<segment>.*), /${segment}