server:
  port: 8088


medilabo:
  security:
    internal-header: ${INTERNAL_HEADER_NAME:X-Internal-Secret}
    internal-secret: ${INTERNAL_SECRET_VALUE:MonSecretSecurise123!}

spring:
  security:
    user:
      name: ${GATEWAY_USER:authorized-client}
      password: ${GATEWAY_PASSWORD:SuperSecretPassword2025!}
  application:
    name: ms-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        #   ROUTE SERVICE PATIENT
        - id: patient-service-route
          uri: lb://MS-PATIENT
          predicates:
            - Path=/api/patient/**
          filters:
            # On r√©√©crit le chemin
            - RewritePath=/api/(?<segment>.*), /${segment}
            # üõ°Ô∏è S√©curit√© : on nettoie ce qui vient de l'ext√©rieur
            - RemoveRequestHeader=${medilabo.security.internal-header}
            # üîë On ajoute notre secret (en utilisant la variable du haut)
            - AddRequestHeader=${medilabo.security.internal-header}, ${medilabo.security.internal-secret}

       # ROUTE SERVICE NOTES
        - id: notes-service-route
          uri: lb://MS-NOTES
          predicates:
            - Path=/api/notes/**
          filters:
            - RewritePath=/api/(?<segment>.*), /${segment}
            # üõ°Ô∏è S√©curit√© : on nettoie ce qui vient de l'ext√©rieur
            - RemoveRequestHeader=${medilabo.security.internal-header}
            # üîë On ajoute notre secret (en utilisant la variable du haut)
            - AddRequestHeader=${medilabo.security.internal-header}, ${medilabo.security.internal-secret}

      # ROUTE SERVICE REPORTS
        - id: report-service-route
          uri: lb://MS-REPORTS
          predicates:
            - Path=/api/report/**
          filters:
            - RewritePath=/api/(?<segment>.*), /${segment}
            # üõ°Ô∏è S√©curit√© : on nettoie ce qui vient de l'ext√©rieur
            - RemoveRequestHeader=${medilabo.security.internal-header}
            # üîë On ajoute notre secret (en utilisant la variable du haut)
            - AddRequestHeader=${medilabo.security.internal-header}, ${medilabo.security.internal-secret}

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:8761/eureka/
  instance:
    prefer-ip-address: true